<?php

namespace Tdom\MessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMessageRepository extends EntityRepository
{

    /**
     * Find User message
     *
     * @param $sourceUserId
     * @param $targetUserId
     * @return array
     */
    public function findUserMessages($sourceUserId, $targetUserId) {
        $qb = $this->createQueryBuilder('um')
              ->innerJoin('um.message', 'm')
              ->where('(um.sourceUser = :sourceUser and um.targetUser = :targetUser)
                  or (um.sourceUser = :targetUser and um.targetUser = :sourceUser)')
              ->setParameter('sourceUser', $sourceUserId)->setParameter('targetUser', $targetUserId)
              ->andWhere('m.isDeleted = :isDeleted')->setParameter('isDeleted' , false);

        return $qb->getQuery()->getResult();
    }
}
